export enum AppErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  HTTP_EXCEPTION = 'HTTP_EXCEPTION',
  INVALID_REQUEST = 'INVALID_REQUEST',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  VENDOR_NOT_FOUND = 'VENDOR_NOT_FOUND',
  BOOTH_NOT_FOUND = 'BOOTH_NOT_FOUND',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  FAVORITE_EXISTS = 'FAVORITE_EXISTS',
  FAVORITE_NOT_FOUND = 'FAVORITE_NOT_FOUND',
}
