export enum AppErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  HTTP_EXCEPTION = 'HTTP_EXCEPTION',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  BOOK_NOT_FOUND = 'BOOK_NOT_FOUND',
  WECHAT_AUTH_FAILED = 'WECHAT_AUTH_FAILED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
}
