export enum AppErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  HTTP_EXCEPTION = 'HTTP_EXCEPTION',
  UNAUTHORIZED = 'UNAUTHORIZED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  HOUSE_NOT_FOUND = 'HOUSE_NOT_FOUND',
  BUILDING_NOT_FOUND = 'BUILDING_NOT_FOUND',
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  DISCLOSURE_CONTENT_NOT_FOUND = 'DISCLOSURE_CONTENT_NOT_FOUND',
  VOTE_NOT_FOUND = 'VOTE_NOT_FOUND',
  INVALID_OPERATION = 'INVALID_OPERATION',
}
