export const ROUTES = {
  login: '/pages/login/index',
  register: '/pages/register/index',
  home: '/pages/home/index',
  voting: {
    index: '/pages/voting/index',
    detail: '/pages/voting/detail/index',
    create: '/pages/voting/create/index',
  },
  assistant: '/pages/assistant/index',
  disclosure: {
    index: '/pages/disclosure/index',
    announcements: '/pages/disclosure/announcements/index',
    detail: '/pages/disclosure/detail/index',
    financial: '/pages/disclosure/financial/index',
    payment: '/pages/disclosure/payment/index',
    management: '/pages/disclosure/management/index',
    maintenance: '/pages/disclosure/maintenance/index',
  },
  profile: {
    index: '/pages/profile/index',
    bind: '/pages/profile/bind/index',
    members: '/pages/profile/members/index',
    invite: '/pages/profile/invite/index',
    permissions: '/pages/profile/permissions/index',
    verification: '/pages/profile/verification/index',
    agent: '/pages/profile/agent/index',
    settings: '/pages/profile/settings/index',
  },
  services: {
    repair: '/pages/services/repair/index',
    visitor: '/pages/services/visitor/index',
    access: '/pages/services/access/index',
    parcel: '/pages/services/parcel/index',
    parking: '/pages/services/parking/index',
    neighbor: '/pages/services/neighbor/index',
    contacts: '/pages/services/contacts/index',
    agency: '/pages/services/agency/index',
  },
  legal: {
    privacy: '/pages/legal/privacy/index',
  },
} as const;
